//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabinetDataStore.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class PregledData
    {
        public int PregledId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime PregledDate { get; set; }
        public Nullable<System.DateTime> PRM { get; set; }
        public Nullable<int> Rajdaniq { get; set; }
        public string Operacii { get; set; }
        public string Bolka { get; set; }
        public string Kurvene { get; set; }
        public string Fluor { get; set; }
        public string Drugi { get; set; }
        public string Kolposkopiq { get; set; }
        public string Ehografiq { get; set; }
        public string Rezultati { get; set; }
        public string Terapiq { get; set; }
        public string Preporuki { get; set; }
    
        public virtual PatientData PatientData { get; set; }
    }
}
